// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-bcr3-8eOhB1uxP9b7jlTZ4PkISGW7-A',
    appId: '1:977660744313:web:d41803a6cf6c2f80733aa8',
    messagingSenderId: '977660744313',
    projectId: 'pawsycare',
    authDomain: 'pawsycare.firebaseapp.com',
    storageBucket: 'pawsycare.appspot.com',
    measurementId: 'G-7RF13ELCWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWPJ3YKZMAOEsmjCUAtYdeXCaoP65W8hQ',
    appId: '1:977660744313:android:d29269e339732f17733aa8',
    messagingSenderId: '977660744313',
    projectId: 'pawsycare',
    storageBucket: 'pawsycare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADoLp4mVX1MJXZCPfGVMQhmQ-MsOtrf00',
    appId: '1:977660744313:ios:e736419f194640e0733aa8',
    messagingSenderId: '977660744313',
    projectId: 'pawsycare',
    storageBucket: 'pawsycare.appspot.com',
    iosBundleId: 'com.example.pawsyCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADoLp4mVX1MJXZCPfGVMQhmQ-MsOtrf00',
    appId: '1:977660744313:ios:6624c45fdce5dea1733aa8',
    messagingSenderId: '977660744313',
    projectId: 'pawsycare',
    storageBucket: 'pawsycare.appspot.com',
    iosBundleId: 'com.example.pawsyCare.RunnerTests',
  );
}
